# SNMP
- platform: snmp
  name: Rack UPS Voltage
  unique_id: sensor.rack_ups_voltage
  host: 192.168.1.197
  version: "1"
  community: !secret ups_rack_snmp_read_community
  baseoid: 1.3.6.1.4.1.318.1.1.1.4.2.1.0 #upsAdvOutputVoltage
  device_class: voltage
  unit_of_measurement: V
  accept_errors: true
  default_value: "0"
- platform: snmp
  name: Rack UPS Current
  unique_id: sensor.rack_ups_current
  host: 192.168.1.197
  version: "1"
  community: !secret ups_rack_snmp_read_community
  baseoid: 1.3.6.1.4.1.318.1.1.1.4.2.4.0 #upsAdvOutputCurrent
  device_class: current
  unit_of_measurement: A
  accept_errors: true
  default_value: "0"
- platform: snmp
  name: Rack UPS Power
  unique_id: sensor.rack_ups_power
  host: 192.168.1.197
  version: "1"
  community: !secret ups_rack_snmp_read_community
  baseoid: 1.3.6.1.4.1.318.1.1.1.4.2.8.0 #upsAdvOutputActivePower
  device_class: power
  unit_of_measurement: W
  accept_errors: true
  default_value: "0"
- platform: snmp
  name: Network PDU Power
  unique_id: sensor.network_pdu_power
  version: "1"
  host: 192.168.1.194
  community: !secret pdu_rack_network_snmp_read_community
  baseoid: 1.3.6.1.4.1.3808.1.1.3.2.3.1.1.7.1 #ePDULoadStatusActivePower
  device_class: power
  unit_of_measurement: W
  accept_errors: true
  default_value: "0"
