# SNMP
- platform: snmp
  name: Network PDU Outlet 1
  version: "1"
  host: 192.168.1.194
  community: !secret pdu_rack_network_snmp_read_write_community
  baseoid: 1.3.6.1.4.1.3808.1.1.6.6.1.5.1.5.1
  payload_on: 1
  payload_off: 2
- platform: snmp
  name: Network PDU Outlet 2
  version: "1"
  host: 192.168.1.194
  community: !secret pdu_rack_network_snmp_read_write_community
  baseoid: 1.3.6.1.4.1.3808.1.1.6.6.1.5.1.5.2
  payload_on: 1
  payload_off: 2
- platform: snmp
  name: Network PDU Outlet 3
  version: "1"
  host: 192.168.1.194
  community: !secret pdu_rack_network_snmp_read_write_community
  baseoid: 1.3.6.1.4.1.3808.1.1.6.6.1.5.1.5.3
  payload_on: 1
  payload_off: 2
- platform: snmp
  name: Network PDU Outlet 4
  version: "1"
  host: 192.168.1.194
  community: !secret pdu_rack_network_snmp_read_write_community
  baseoid: 1.3.6.1.4.1.3808.1.1.6.6.1.5.1.5.4
  payload_on: 1
  payload_off: 2
- platform: snmp
  name: Network PDU Outlet 5
  version: "1"
  host: 192.168.1.194
  community: !secret pdu_rack_network_snmp_read_write_community
  baseoid: 1.3.6.1.4.1.3808.1.1.6.6.1.5.1.5.5
  payload_on: 1
  payload_off: 2
- platform: snmp
  name: Network PDU Outlet 6
  version: "1"
  host: 192.168.1.194
  community: !secret pdu_rack_network_snmp_read_write_community
  baseoid: 1.3.6.1.4.1.3808.1.1.6.6.1.5.1.5.6
  payload_on: 1
  payload_off: 2
- platform: snmp
  name: Network PDU Outlet 7
  version: "1"
  host: 192.168.1.194
  community: !secret pdu_rack_network_snmp_read_write_community
  baseoid: 1.3.6.1.4.1.3808.1.1.6.6.1.5.1.5.7
  payload_on: 1
  payload_off: 2
- platform: snmp
  name: Network PDU Outlet 8
  version: "1"
  host: 192.168.1.194
  community: !secret pdu_rack_network_snmp_read_write_community
  baseoid: 1.3.6.1.4.1.3808.1.1.6.6.1.5.1.5.8
  payload_on: 1
  payload_off: 2
